# Generated by Django 3.2.15 on 2022-10-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
